# This is a basic timing constriant file
set_time_format -unit ns -decimal_places 3

# 100MHz input clock
create_clock -name {clk_100m} -period 10.000 -waveform { 0.000 5.000 } [get_ports {clk_100m}]
set_clock_uncertainty -rise_from [get_clocks {clk_100m}] -rise_to [get_clocks {clk_100m}]  0.020  
set_clock_uncertainty -rise_from [get_clocks {clk_100m}] -fall_to [get_clocks {clk_100m}]  0.020  
set_clock_uncertainty -fall_from [get_clocks {clk_100m}] -rise_to [get_clocks {clk_100m}]  0.020  
set_clock_uncertainty -fall_from [get_clocks {clk_100m}] -fall_to [get_clocks {clk_100m}]  0.020  

# Clocks generated by PLL
derive_pll_clocks -create_base_clocks
